# Generated by Django 2.2 on 2020-06-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthrecording',
            options={'ordering': ['-date_modified']},
        ),
    ]
